# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_test', [dirname(__file__)])
        except ImportError:
            import _test
            return _test
        if fp is not None:
            try:
                _mod = imp.load_module('_test', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _test = swig_import_helper()
    del swig_import_helper
else:
    import _test
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _test.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _test.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _test.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _test.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _test.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _test.SwigPyIterator_equal(self, x)

    def copy(self):
        return _test.SwigPyIterator_copy(self)

    def next(self):
        return _test.SwigPyIterator_next(self)

    def __next__(self):
        return _test.SwigPyIterator___next__(self)

    def previous(self):
        return _test.SwigPyIterator_previous(self)

    def advance(self, n):
        return _test.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _test.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _test.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _test.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _test.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _test.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _test.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _test.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _test.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _test.VecDouble___nonzero__(self)

    def __bool__(self):
        return _test.VecDouble___bool__(self)

    def __len__(self):
        return _test.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _test.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _test.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _test.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _test.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _test.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _test.VecDouble___setitem__(self, *args)

    def pop(self):
        return _test.VecDouble_pop(self)

    def append(self, x):
        return _test.VecDouble_append(self, x)

    def empty(self):
        return _test.VecDouble_empty(self)

    def size(self):
        return _test.VecDouble_size(self)

    def swap(self, v):
        return _test.VecDouble_swap(self, v)

    def begin(self):
        return _test.VecDouble_begin(self)

    def end(self):
        return _test.VecDouble_end(self)

    def rbegin(self):
        return _test.VecDouble_rbegin(self)

    def rend(self):
        return _test.VecDouble_rend(self)

    def clear(self):
        return _test.VecDouble_clear(self)

    def get_allocator(self):
        return _test.VecDouble_get_allocator(self)

    def pop_back(self):
        return _test.VecDouble_pop_back(self)

    def erase(self, *args):
        return _test.VecDouble_erase(self, *args)

    def __init__(self, *args):
        this = _test.new_VecDouble(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _test.VecDouble_push_back(self, x)

    def front(self):
        return _test.VecDouble_front(self)

    def back(self):
        return _test.VecDouble_back(self)

    def assign(self, n, x):
        return _test.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _test.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _test.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _test.VecDouble_reserve(self, n)

    def capacity(self):
        return _test.VecDouble_capacity(self)
    __swig_destroy__ = _test.delete_VecDouble
    __del__ = lambda self: None
VecDouble_swigregister = _test.VecDouble_swigregister
VecDouble_swigregister(VecDouble)

class mat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _test.mat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _test.mat___nonzero__(self)

    def __bool__(self):
        return _test.mat___bool__(self)

    def __len__(self):
        return _test.mat___len__(self)

    def __getslice__(self, i, j):
        return _test.mat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _test.mat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _test.mat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _test.mat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _test.mat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _test.mat___setitem__(self, *args)

    def pop(self):
        return _test.mat_pop(self)

    def append(self, x):
        return _test.mat_append(self, x)

    def empty(self):
        return _test.mat_empty(self)

    def size(self):
        return _test.mat_size(self)

    def swap(self, v):
        return _test.mat_swap(self, v)

    def begin(self):
        return _test.mat_begin(self)

    def end(self):
        return _test.mat_end(self)

    def rbegin(self):
        return _test.mat_rbegin(self)

    def rend(self):
        return _test.mat_rend(self)

    def clear(self):
        return _test.mat_clear(self)

    def get_allocator(self):
        return _test.mat_get_allocator(self)

    def pop_back(self):
        return _test.mat_pop_back(self)

    def erase(self, *args):
        return _test.mat_erase(self, *args)

    def __init__(self, *args):
        this = _test.new_mat(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _test.mat_push_back(self, x)

    def front(self):
        return _test.mat_front(self)

    def back(self):
        return _test.mat_back(self)

    def assign(self, n, x):
        return _test.mat_assign(self, n, x)

    def resize(self, *args):
        return _test.mat_resize(self, *args)

    def insert(self, *args):
        return _test.mat_insert(self, *args)

    def reserve(self, n):
        return _test.mat_reserve(self, n)

    def capacity(self):
        return _test.mat_capacity(self)
    __swig_destroy__ = _test.delete_mat
    __del__ = lambda self: None
mat_swigregister = _test.mat_swigregister
mat_swigregister(mat)

class moo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, moo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, moo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["one"] = _test.moo_one_set
    __swig_getmethods__["one"] = _test.moo_one_get
    if _newclass:
        one = _swig_property(_test.moo_one_get, _test.moo_one_set)

    def __init__(self):
        this = _test.new_moo()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _test.delete_moo
    __del__ = lambda self: None
moo_swigregister = _test.moo_swigregister
moo_swigregister(moo)


def average(matrix):
    return _test.average(matrix)
average = _test.average
# This file is compatible with both classic and new-style classes.


