import os
import sipconfig
from PyQt5 import QtCore

# The name of the SIP build file generated by SIP and used by the build
# system.

# run `find . -name "qstring.*"` at `/usr`
# directory of `qstring.sip` is the `sip_inc_dir`
sip_inc_dir = "/usr/share/sip/PyQt5/"
# directory of `qstring.h` is the `qt5_inc_dir`
qt5_inc_dir = "/usr/include/x86_64-linux-gnu/qt5/"

lib_name = "png_reader"
build_file = "{}.sbf".format(lib_name)

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([
    # using sip binary
    config.sip_bin,

    # in the current directory as root
    "-c", ".",

    # generate the build file
    "-b", build_file,

    # including these headers (contain Qt SIP definitions)
    "-I{}".format(sip_inc_dir),

    # Match installed PyQt configuration
    QtCore.PYQT_CONFIGURATION["sip_flags"],

    # name of the library to generate
    "{}.sip".format(lib_name)
]))
target_dir = os.path.abspath(os.getcwd() + "/../src")
custom_lib_dir = os.path.abspath(os.getcwd() + "/../../libs")

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

extra_flags = "-std=c++11 -I{} -I{} -I{}/QtCore".format(custom_lib_dir,
                                                        qt5_inc_dir,
                                                        qt5_inc_dir)
makefile.extra_cflags = [extra_flags]
makefile.extra_cxxflags = [extra_flags]
makefile.extra_lib_dirs = [target_dir, custom_lib_dir]

# Extra libraries to be linked. Their source needs to be
# added to `makefile.extra_lib_dirs` if not on LD_LIBRARY_PATH
makefile.extra_libs = ["lodepng"]

makefile.generate()

# makefile.extra_lflags = ["-Wl,-R{}".format(target_dir), "-Wl,-R{}".format(custom_lib_dir)]
# Generate the Makefile itself.
