import os
import sipconfig
from PyQt5 import QtCore

# The name of the SIP build file generated by SIP and used by the build
# system.
lib_name = "png_reader"
build_file = "{}.sbf".format(lib_name)

# run `find . -name "qstring.*"` at `/usr`
# directory of `qstring.sip` is the `sip_inc_dir`
sip_inc_dir = "/usr/share/sip/PyQt5/"
# directory of `qstring.h` is the `qt5_inc_dir`
qt5_inc_dir = "/usr/include/x86_64-linux-gnu/qt5/"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin,
                    "-c", ".",
                    "-b", build_file,
                    "-I{}".format(sip_inc_dir),
                    QtCore.PYQT_CONFIGURATION["sip_flags"],
                    "{}.sip".format(lib_name)
                    ]))
target_dir = os.path.abspath(os.getcwd() + "/../src")
custom_lib_dir = os.path.abspath(os.getcwd() + "/../../libs")

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

extra_flags = "-std=c++11 -I{} -I{} -I{}/QtCore".format(custom_lib_dir, qt5_inc_dir, qt5_inc_dir)
makefile.extra_cflags = [extra_flags]
makefile.extra_cxxflags = [extra_flags]
# makefile.extra_lflags = ["-Wl,-R{}".format(target_dir), "-Wl,-R{}".format(custom_lib_dir)]
makefile.extra_lib_dirs = [target_dir, custom_lib_dir]
# makefile.extra_libs = ["lodepng"]

# Generate the Makefile itself.
makefile.generate()
