/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.7
 */

#ifndef _png_readerAPI_H
#define _png_readerAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_5_9_5


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_std__string 0
#define sipName_std__string &sipStrings_png_reader[0]
#define sipNameNr_png_reader 12
#define sipName_png_reader &sipStrings_png_reader[12]
#define sipNameNr_directory 23
#define sipName_directory &sipStrings_png_reader[23]
#define sipNameNr_precision 33
#define sipName_precision &sipStrings_png_reader[33]
#define sipNameNr_nameType 43
#define sipName_nameType &sipStrings_png_reader[43]
#define sipNameNr_filters 52
#define sipName_filters &sipStrings_png_reader[52]
#define sipNameNr_enabled 60
#define sipName_enabled &sipStrings_png_reader[60]
#define sipNameNr_options 68
#define sipName_options &sipStrings_png_reader[68]
#define sipNameNr_proper 76
#define sipName_proper &sipStrings_png_reader[76]
#define sipNameNr_value9 83
#define sipName_value9 &sipStrings_png_reader[83]
#define sipNameNr_value8 90
#define sipName_value8 &sipStrings_png_reader[90]
#define sipNameNr_value7 97
#define sipName_value7 &sipStrings_png_reader[97]
#define sipNameNr_value6 104
#define sipName_value6 &sipStrings_png_reader[104]
#define sipNameNr_value5 111
#define sipName_value5 &sipStrings_png_reader[111]
#define sipNameNr_value4 118
#define sipName_value4 &sipStrings_png_reader[118]
#define sipNameNr_value3 125
#define sipName_value3 &sipStrings_png_reader[125]
#define sipNameNr_value2 132
#define sipName_value2 &sipStrings_png_reader[132]
#define sipNameNr_value1 139
#define sipName_value1 &sipStrings_png_reader[139]
#define sipNameNr_value0 146
#define sipName_value0 &sipStrings_png_reader[146]
#define sipNameNr_symbol 153
#define sipName_symbol &sipStrings_png_reader[153]
#define sipNameNr_suffix 160
#define sipName_suffix &sipStrings_png_reader[160]
#define sipNameNr_prefix 167
#define sipName_prefix &sipStrings_png_reader[167]
#define sipNameNr_string 5
#define sipName_string &sipStrings_png_reader[5]
#define sipNameNr_locale 174
#define sipName_locale &sipStrings_png_reader[174]
#define sipNameNr_format 181
#define sipName_format &sipStrings_png_reader[181]
#define sipNameNr_object 188
#define sipName_object &sipStrings_png_reader[188]
#define sipNameNr_World 195
#define sipName_World &sipStrings_png_reader[195]
#define sipNameNr_msecs 201
#define sipName_msecs &sipStrings_png_reader[201]
#define sipNameNr_mode 207
#define sipName_mode &sipStrings_png_reader[207]
#define sipNameNr_name 212
#define sipName_name &sipStrings_png_reader[212]
#define sipNameNr_base 217
#define sipName_base &sipStrings_png_reader[217]
#define sipNameNr_from 222
#define sipName_from &sipStrings_png_reader[222]
#define sipNameNr_sort 227
#define sipName_sort &sipStrings_png_reader[227]
#define sipNameNr_get 232
#define sipName_get &sipStrings_png_reader[232]
#define sipNameNr_set 236
#define sipName_set &sipStrings_png_reader[236]

#define sipMalloc                   sipAPI_png_reader->api_malloc
#define sipFree                     sipAPI_png_reader->api_free
#define sipBuildResult              sipAPI_png_reader->api_build_result
#define sipCallMethod               sipAPI_png_reader->api_call_method
#define sipCallProcedureMethod      sipAPI_png_reader->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_png_reader->api_call_error_handler
#define sipParseResultEx            sipAPI_png_reader->api_parse_result_ex
#define sipParseResult              sipAPI_png_reader->api_parse_result
#define sipParseArgs                sipAPI_png_reader->api_parse_args
#define sipParseKwdArgs             sipAPI_png_reader->api_parse_kwd_args
#define sipParsePair                sipAPI_png_reader->api_parse_pair
#define sipInstanceDestroyed        sipAPI_png_reader->api_instance_destroyed
#define sipConvertFromSequenceIndex sipAPI_png_reader->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_png_reader->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_png_reader->api_convert_to_void_ptr
#define sipAddException             sipAPI_png_reader->api_add_exception
#define sipNoFunction               sipAPI_png_reader->api_no_function
#define sipNoMethod                 sipAPI_png_reader->api_no_method
#define sipAbstractMethod           sipAPI_png_reader->api_abstract_method
#define sipBadClass                 sipAPI_png_reader->api_bad_class
#define sipBadCatcherResult         sipAPI_png_reader->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_png_reader->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_png_reader->api_bad_operator_arg
#define sipTrace                    sipAPI_png_reader->api_trace
#define sipTransferBack             sipAPI_png_reader->api_transfer_back
#define sipTransferTo               sipAPI_png_reader->api_transfer_to
#define sipTransferBreak            sipAPI_png_reader->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_png_reader->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_png_reader->api_wrapper_type
#define sipWrapperType_Type         sipAPI_png_reader->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_png_reader->api_voidptr_type
#define sipGetPyObject              sipAPI_png_reader->api_get_pyobject
#define sipGetAddress               sipAPI_png_reader->api_get_address
#define sipGetMixinAddress          sipAPI_png_reader->api_get_mixin_address
#define sipGetCppPtr                sipAPI_png_reader->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_png_reader->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_png_reader->api_is_py_method
#define sipCallHook                 sipAPI_png_reader->api_call_hook
#define sipEndThread                sipAPI_png_reader->api_end_thread
#define sipConnectRx                sipAPI_png_reader->api_connect_rx
#define sipDisconnectRx             sipAPI_png_reader->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_png_reader->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_png_reader->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_png_reader->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_png_reader->api_add_type_instance
#define sipFreeSipslot              sipAPI_png_reader->api_free_sipslot
#define sipSameSlot                 sipAPI_png_reader->api_same_slot
#define sipPySlotExtend             sipAPI_png_reader->api_pyslot_extend
#define sipConvertRx                sipAPI_png_reader->api_convert_rx
#define sipAddDelayedDtor           sipAPI_png_reader->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_png_reader->api_can_convert_to_type
#define sipConvertToType            sipAPI_png_reader->api_convert_to_type
#define sipForceConvertToType       sipAPI_png_reader->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_png_reader->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_png_reader->api_convert_to_enum
#define sipConvertToBool            sipAPI_png_reader->api_convert_to_bool
#define sipReleaseType              sipAPI_png_reader->api_release_type
#define sipConvertFromType          sipAPI_png_reader->api_convert_from_type
#define sipConvertFromNewType       sipAPI_png_reader->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_png_reader->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_png_reader->api_convert_from_enum
#define sipGetState                 sipAPI_png_reader->api_get_state
#define sipExportSymbol             sipAPI_png_reader->api_export_symbol
#define sipImportSymbol             sipAPI_png_reader->api_import_symbol
#define sipFindType                 sipAPI_png_reader->api_find_type
#define sipFindNamedEnum            sipAPI_png_reader->api_find_named_enum
#define sipBytes_AsChar             sipAPI_png_reader->api_bytes_as_char
#define sipBytes_AsString           sipAPI_png_reader->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_png_reader->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_png_reader->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_png_reader->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_png_reader->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_png_reader->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_png_reader->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_png_reader->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_png_reader->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_png_reader->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_png_reader->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_png_reader->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_png_reader->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_png_reader->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_png_reader->api_save_slot
#define sipClearAnySlotReference    sipAPI_png_reader->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_png_reader->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_png_reader->api_deprecated
#define sipGetReference             sipAPI_png_reader->api_get_reference
#define sipKeepReference            sipAPI_png_reader->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_png_reader->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_png_reader->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_png_reader->api_type_from_py_type_object
#define sipTypeScope                sipAPI_png_reader->api_type_scope
#define sipResolveTypedef           sipAPI_png_reader->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_png_reader->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_png_reader->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_png_reader->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_png_reader->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_png_reader->api_enable_overflow_checking
#define sipInitMixin                sipAPI_png_reader->api_init_mixin
#define sipExportModule             sipAPI_png_reader->api_export_module
#define sipInitModule               sipAPI_png_reader->api_init_module
#define sipGetInterpreter           sipAPI_png_reader->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_png_reader->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_png_reader->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_png_reader->api_get_type_user_data
#define sipPyTypeDict               sipAPI_png_reader->api_py_type_dict
#define sipPyTypeName               sipAPI_png_reader->api_py_type_name
#define sipGetCFunction             sipAPI_png_reader->api_get_c_function
#define sipGetMethod                sipAPI_png_reader->api_get_method
#define sipFromMethod               sipAPI_png_reader->api_from_method
#define sipGetDate                  sipAPI_png_reader->api_get_date
#define sipFromDate                 sipAPI_png_reader->api_from_date
#define sipGetDateTime              sipAPI_png_reader->api_get_datetime
#define sipFromDateTime             sipAPI_png_reader->api_from_datetime
#define sipGetTime                  sipAPI_png_reader->api_get_time
#define sipFromTime                 sipAPI_png_reader->api_from_time
#define sipIsUserType               sipAPI_png_reader->api_is_user_type
#define sipGetFrame                 sipAPI_png_reader->api_get_frame
#define sipCheckPluginForType       sipAPI_png_reader->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_png_reader->api_unicode_new
#define sipUnicodeWrite             sipAPI_png_reader->api_unicode_write
#define sipUnicodeData              sipAPI_png_reader->api_unicode_data
#define sipGetBufferInfo            sipAPI_png_reader->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_png_reader->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_png_reader->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_png_reader->api_is_derived_class
#define sipGetUserObject            sipAPI_png_reader->api_get_user_object
#define sipSetUserObject            sipAPI_png_reader->api_set_user_object
#define sipRegisterEventHandler     sipAPI_png_reader->api_register_event_handler
#define sipLong_AsChar              sipAPI_png_reader->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_png_reader->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_png_reader->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_png_reader->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_png_reader->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_png_reader->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_png_reader->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_png_reader->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_png_reader->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_png_reader->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_png_reader->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_png_reader->api_map_string_to_class
#define sipMapIntToClass            sipAPI_png_reader->api_map_int_to_class
#define sipFindClass                sipAPI_png_reader->api_find_class
#define sipFindMappedType           sipAPI_png_reader->api_find_mapped_type
#define sipConvertToArray           sipAPI_png_reader->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_png_reader->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_png_reader->api_enable_gc
#define sipPrintObject              sipAPI_png_reader->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_png_reader->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_png_reader[];

#define sipType_World sipExportedTypes_png_reader[0]
#define sipClass_World sipExportedTypes_png_reader[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_png_reader_World;

#define sipType_std_string sipExportedTypes_png_reader[1]

extern sipMappedTypeDef sipTypeDef_png_reader_std_string;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_png_reader;
extern sipExportedModuleDef sipModuleAPI_png_reader;
extern sipTypeDef *sipExportedTypes_png_reader[];

#define sipType_QString sipImportedTypes_png_reader_QtCore[0].it_td
extern sipImportedTypeDef sipImportedTypes_png_reader_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_png_reader_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_png_reader_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_png_reader_qt_metacast;

#endif
